apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: 
    tier: db
  namespace: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: db
      project: roboshop
      component: mysql
  template:
    metadata:
      labels:
        app: db
        project: roboshop
        component: mysql
    spec:
      containers:
      - name: mysql
        image: klkreddy123/mysql:1.0.0
        envFrom:
        - configMapRef:
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
        app: db
        project: roboshop
        component: mysql
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"