apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: 
    tier: app
  namespace: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: app
      project: roboshop
      component: catalogue
  template:
    metadata:
      labels:
        app: app
        project: roboshop
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: klkreddy123/catalogue:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec:
  selector:
        app: db
        project: roboshop
        component: catalogue
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO="true"
  MONGO_URL="mongodb:mongodb//:27017/catalogue"