apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
    project: roboshop
    component: web
  namespace: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: web
      project: roboshop
      component: web
  template:
    metadata:
      labels:
        app: web
        project: roboshop
        component: web
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: web
        image: klkreddy123/web:1.0.0
        volumeMounts:  
          - name: nginx-conf # name of the volume you created above
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
        app: web
        project: roboshop
        component: web
  ports:
  - name: web-port
    protocol: TCP
    port: 80
    targetPort: 80