apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: 
    tier: db
  namespace: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: db
      project: roboshop
      component: redis
  template:
    metadata:
      labels:
        app: db
        project: roboshop
        component: redis
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
        app: db
        project: roboshop
        component: redis
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379