apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: 
    tier: db
  Namespace: roboshop
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: db
      project: roboshop
      component: mongodb
  template:
    metadata:
      labels:
        app: db
        project: roboshop
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: klkreddy123/mongodb:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
        app: db
        project: roboshop
        component: mongodb
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017