apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    course: devops
    duration: 100hrs
    trainer: siva
spec:
  containers:
    - name: label
      image: nginx
      ports:
        - containerPort: 80