apiVersion: v1
kind: Pod
metadata:
  name: resources
  spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always  
      resources:
        requests:
          cpu: "64m"
          memory: "128Mi"
        limits:
          cpu: "128m"
          memory: "256Mi"