apiVersion: v1
kind: Pod
metadata:
  name: config-nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: What_is_the_course_name
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: COURSE
        - name: Duration_of_the_course
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: DURATION
        - name: Who_taught_the_course
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: TRAINER